### PR TITLE
Added BinarySearchtree

### PR DESCRIPTION
**Pull request by Souravirus**
i have added a program of binary search tree #4

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @Souravirus 
your code is well intended and readable .
try to give one line gap between two fuctions

**Comment by Souravirus** [comment]
added space betweeen lines as you said

**Comment by srbcheema1** [comment]
ok great work @Souravirus 
thanks alot

**Comment by srbcheema1** [comment]
i am merging your pull request

**Pull request merged**
