### PR TITLE
Corrected grammar #16

### PR DESCRIPTION
**Pull request by SemicolonExpected**
-"it also includes some very useful algorithms" is redundant since we already said it here: "it contains many advanced algorithms and data structures like"

- Split up the contents into two groups: Algorithms and Data Structure

- changed "at last star this repo because this will be handy for you" to "Star this repo if this will be handy for you" because the "At last is unnecessary, and changed because to if as to sound more approachable and less demanding.

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @SemicolonExpected 
your pull request is having few conflicts .
can you resolve them so that i can merge your PR without conflicts

**Comment by SemicolonExpected** [comment]
I only see one conflict and it's that "only those with write access can merge pull requests" which means only you can merge them I think.

**Comment by srbcheema1** [comment]
ok i have done that ;) 
you could have done that by pulling my master branch and merging it with your branch .

**Comment by srbcheema1** [comment]
thanks for the contribution :)
and dont forget to give my repository a STAR .

**Pull request merged**
