### PR TITLE
Create bogosort.py

### PR DESCRIPTION
**Pull request by alexandrebarbaruiva**
Adding python implementation of bogosort

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @alexandrebarbaruiva 
you are doing great :+1:

**Comment by srbcheema1** [comment]
sorry @alexandrebarbaruiva 
i pressed the close button by mistake :disappointed: 
can you reopen the PR so that i can merge your PR

**Comment by alexandrebarbaruiva** [comment]
I don't see any reopen button 😢  I think only you can reopen!

**Comment by srbcheema1** [comment]
you have deleted the branch :disappointed: 
thats why i too cannot reopen it again 
you can do one thing send the PR again

**Pull request closed without merging**
