### PR TITLE
SIMPLE FACTORIAL #3

### PR DESCRIPTION
**Pull request by rishabh-bansal**
Given N numbers, calculate sum of their factorial modulo 107.

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for PR @rishabh-bansal . 
i am happy for your contributions to this repository .
your previous PR of sorting algorithms was awesome I appreciate that.
but this code is very small and is not used commonly .
you may modify it bit .

**Comment by rishabh-bansal** [comment]
@srbcheema1  For sure my friend! :)

**Comment by srbcheema1** [comment]
@rishabh-bansal 
in the discription of your PR 
also mention that your PR belongs to issue #2

**Comment by srbcheema1** [comment]
@rishabh-bansal i am glad to see your dedication towards algorithms 
try to keep names of your files as filename.cpp
i would suggest you to work on sorting and searching algorithms .

**Pull request closed without merging**
