### PR TITLE
Created graph.py

### PR DESCRIPTION
**Pull request by bigpythonimish**

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @bigpythonimish 
your code is really awesome well commented and readable
i would love to see more contributions from your side in python language

**Comment by srbcheema1** [comment]
i would be glad if you give a STAR to this repository

**Comment by bigpythonimish** [comment]
Sure check out some of my work in Python too

**Comment by srbcheema1** [comment]
surely i will :+1:

**Pull request merged**
