### PR TITLE
Basic DP problems added

### PR DESCRIPTION
**Pull request by flaredragon**
Dynamic Programming Problems Added-
1) Coin Change Problem
2) Longest Common Subsequence Problem

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @flaredragon 
your code is perfectly commented and intended 
it iis awesome and readable .
i am merging this pull request 
and i would like to have more contributions from your side

**Comment by srbcheema1** [comment]
@flaredragon 
also donot forget to give STAR to this repo

**Comment by flaredragon** [comment]
Done, It would also be nice if we could work on building some open source software during Hacktoberfest for any user to easily access these algorithms.

**Comment by srbcheema1** [comment]
@flaredragon 
that would be great idea
but can you give a basic idea how to begin with or on what platform(android , web or console app) should we start .
any blueprint of the idea in your mind

**Pull request merged**
