### PR TITLE
PR for Hacktoberfest: Added Program to find all primes without checking all numbers

### PR DESCRIPTION
**Pull request by Vehemos**
All primes are of form 6*k +- 1, instead of doing primality test on all numbers, the programmer can improve the efficiency of his code by only performing the test on a precomputed list which includes all the primes (with some garbage) minus most of the composite numbers.

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks or the PR @Vehemos 
can you please elaborate the functionality of this code .
we can generate prime numbers in many other ways .
like seive , segmented seive . 
i think your code requires bit modification

**Comment by srbcheema1** [comment]
@Vehemos for now i am merging this pull request .
i would be glad to see more contributions from your side .
and i would also love to see this code completed .
you can add the filter so that you can filer out the garbage numbers generated

**Comment by Vehemos** [comment]
All prime numbers greater than 2 and 3 are of the form 6k + 1 or 6k - 1 only. It does includes some composite numbers in between. Let's say you have a questions of printing all primes upto 10^5. You can use Sieves I am taking Sieve of Eratosthenes as an example, you can use a bool array and mark non-primes after going through all of them, using this approach you already have a list of all prime numbers (with some rare garbage) so you don't have to go over all the numbers, and that increases your efficiency.
You can test the time difference by using --time flag in your compiler.

**Comment by Vehemos** [comment]
@srbcheema1 If I apply a filter then it will become a different code altogether (Like a Sieve + This) Are you sure you want me to do that? I just wanted to make prime finding easier for competitive coders and provided this as an example.

**Comment by srbcheema1** [comment]
yeah i got that point .
thats why i merged that PR.
it is ok . you may update the code by creating a function that creates a list of numbers of such type(prime numbers + garbage )
and a function that take a array as input and remove the garbage . 
i would also be happy to see more contributions from your side

**Pull request merged**
